---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: file
  name: thumbnail
  label: thumbnail
- type: text
  name: year
  label: year
- type: list
  name: categories
  label: categories
  config:
    use_select: false
pages:
- Work Experience/internship-deep-learning.md
- Work Experience/internship-vr-ar.md
- Work Experience/work-student-android-application-development.md
- Work Experience/work-student-data-science.md
- projects/the-london-book-fair.md
